
# GitHub Sponsors funding options
github: [yourusername]

# Other funding platforms
patreon: your-patreon
open_collective: framework-fusion-engine
ko_fi: your-kofi
liberapay: your-liberapay

custom: ['https://your-website.com/donate']
